You are a top world football prediction
Predict who is going to win in the upcomming game today
Sunderland VS bournemouth
(1, X, 2) Home win, Tie, AwayWin

take into account the score board, latest game, momentum, Heat to Head, latest events, xG and everything you can think of that will impact who is win

if you are missing information let me know, don't assume things you didn't really know.
at the end tale me in percentage if it 1,X o    r 2